#!/bin/bash

cmd-ip() {
	local interface="$1";
	if [ -z $interface ]; then
		interface="eth0"
	fi
	ip=$(ifconfig $interface | awk -F ' *|:' '/inet addr/{print $4}')
	echo $ip
}

cmd-bootstrap() {
	local ip=$(cmd-ip $1)
	docker run --rm progrium/consul cmd:run $ip -d
}

cmd-join() {
	local interface="$1";
	local join="$2";
}

cmd-dockeropts() {
	local bridge_ip="$(ip ro | grep docker | awk '{print $9}')"
	echo "DOCKER_OPTS='--dns $bridge_ip --dns 8.8.8.8 --dns-search service.consul'" > /etc/default/docker
	service docker restart
}

cmd-help() {
	echo
    cat<<EOF
    help                        Print the list of commands
    ip [interface]              Print the IP address for a given interface
    bootstrap [interface]       Start a new cluster
    join [interface] [joinip]   Join an existing cluster
    dockeropts [interface]      Update docker to run with the consul DNS and HTTP api
EOF
	echo
}

main() {
	set -eo pipefail
	case "$1" in
	ip)			  					shift; cmd-ip "$@";;
	bootstrap)					shift; cmd-bootstrap "$@";;
	join)								shift; cmd-join "$@";;
	dockeropts)					shift; cmd-dockeropts "$@";;
	*)                  cmd-help "$@";;
	esac
}

main "$@"