#!/bin/bash

#readonly IMAGE="progrium/consulate"
readonly NAME="smesh"

start() {
	echo "hello"
}

main() {
	set -eo pipefail
	case "$1" in
	#cmd:run)            shift; cmd-run "$@";;
	*)                  start "$@";;
	esac
}

main "$@"